ab1.in
  timeLimit: 1000
  isPretest: false
  score: 20
ab2.in
  timeLimit: 1000
  isPretest: false
  score: 20
ab3.in
  timeLimit: 1000
  isPretest: false
  score: 20
ab4.in
  timeLimit: 1000
  isPretest: false
  score: 20
ab5.in
  timeLimit: 1000
  isPretest: false
  score: 20